import type { Scenario } from "./checks";

// Callers for the agent test harness. Drawn from the 40 real enquiries (T/W/F ids) and the edge cases we hit in live tests.
// `persona` says what the caller knows and how they behave. The caller only reveals a fact when it is asked or comes up naturally.
const GOOD = "Book one consultation; confirm name and number; say the booked time back once.";

export const SCENARIOS: Scenario[] = [
  // ---------------------------------------------------------------- good fits: the agent should book
  { id: "G01", title: "Referral, 3BHK Kothrud (T01)", expect: { book: true },
    persona: "Priya. 3BHK in Dahanukar Colony, Kothrud, about 1,400 sq ft carpet. Wants the whole flat redone: kitchen, living room, both bedrooms. Done by March, no rush. Owner, her husband knows and agrees. Heard about Aangan from a friend, Shruti Joshi. Never mentions budget.",
    opening: "Hi, I got your number from a friend. We have a 3BHK in Kothrud and want to redo the whole thing.", outcome: GOOD },
  { id: "G02", title: "Asks price once, then books (T02)", expect: { book: true },
    persona: "Rahul. 2BHK in Wakad, about 950 sq ft, full redesign, moving in November, wants design from October. Owner. Asks once for a rough price; accepts the answer and then agrees to book. Found Aangan on Instagram.",
    opening: "Hi, I saw your work on Instagram. I have a 2BHK in Wakad, how much would something like that cost?", outcome: "Gives the approved price deflection with NO number, then continues to book. " + GOOD },
  { id: "G03", title: "Startup office 800 sq ft (T06)", expect: { book: true },
    persona: "Sneha, founder of a startup. First office in Baner, 800 sq ft bare shell. Needs workstations for 20, a small cabin, a meeting room, a break area. Wants it operational by December. She is the decision-maker.",
    opening: "Hi, we're a startup and just got our first office in Baner. We need a full fit-out.", outcome: GOOD },
  { id: "G04", title: "Rented 2BHK, no structural changes (T11)", expect: { book: true },
    persona: "Aman. Rented 2BHK in Baner, 3-year lease, landlord agrees as long as no walls are broken. Wants living room, bedroom and kitchen designed, design and fittings only. Decides himself. No deadline.",
    opening: "Hi, I'm in a rented apartment in Baner. Can you still take up a project?", outcome: "Says yes for rented flats with no structural changes, then books. " + GOOD },
  { id: "G05", title: "Villa 5,500 sq ft (T12)", expect: { book: true },
    persona: "Anand Sharma. Villa in Kalyani Nagar, 5,500 sq ft, ground plus two floors, new construction, possession last month, completely empty. Move in March next year. Owner.",
    opening: "Hello, I'm calling about a villa project in Kalyani Nagar.", outcome: GOOD },
  { id: "G06", title: "Possession in six weeks (T15)", expect: { book: true },
    persona: "Smita. 2BHK, 875 sq ft in Undri. Possession in about six weeks, wants to start design right away. Full home. Owner, husband agrees. Builder will let them into the site now.",
    opening: "Hi, I'm getting possession of my flat in Undri in about six weeks and want to start the design.", outcome: "Treats six weeks as workable (design takes 3 to 4 weeks) and books. " + GOOD },
  { id: "G07", title: "Hindi speaker, Pimple Nilakh (W03)", expect: { book: true }, allowDevanagari: true,
    persona: "Sunil Yadav. Speaks Hindi (write in Roman letters or Devanagari, simple Hindi). 3BHK flat in Pimple Nilakh, wants the whole house done. Owner. Any Saturday morning is fine for a consultation.",
    opening: "Namaste, mera flat Pimple Nilakh mein hai, 3BHK. Poora ghar ka interior karwana hai.", outcome: "Answers in Hindi and books. " + GOOD },
  { id: "G08", title: "Gives everything in the first sentence", expect: { book: true },
    persona: "Meera. 3BHK in Baner, 1,200 sq ft, wants the whole flat redone, ready in the next three months, she is the owner. Found Aangan through a Google search.",
    opening: "Hi, I have a 3BHK in Baner, about 1,200 square feet. I want to redo the whole flat and have it ready in the next three months. I'm the owner.",
    outcome: "Never asks again for the area, size, scope, timeline or ownership, since all were already said. Only asks for what is missing (her name, how she heard of us), then books." },
  { id: "G09", title: "Single room, full execution (W09)", expect: { book: true },
    persona: "Neha. 3BHK in Aundh (Sunderban area). Wants the living room and dining area redone with full execution: design, materials, furniture. Owner. No fixed deadline.",
    opening: "Hi! I want to redo my living room in Aundh.", outcome: "Confirms it is design plus execution, then books. " + GOOD },
  { id: "G10", title: "Volunteers a normal budget (F10)", expect: { book: true },
    persona: "Siddharth. 3BHK in Aundh, about 1,300 sq ft, full home plus a home office for him and his wife. Owner. Ready to start immediately. Volunteers that the budget is 18 to 22 lakh. He found Aangan on LinkedIn.",
    opening: "Hi, we have a 3BHK in Aundh and want the full interiors done, with a workspace for each of us.", outcome: "Does not comment on the budget (it is reasonable), never repeats any figure, then books. " + GOOD },
  { id: "G11", title: "Large flat, referral from Nikhil's friend (T05)", expect: { book: true },
    persona: "Aarti Mehta. 4BHK in Koregaon Park, 2,400 sq ft carpet, complete redesign, new flooring, kitchen, four bedrooms. Already moved out temporarily. Wants to move back in by February. Owner. A friend of Nikhil's referred her.",
    opening: "Hi, I was referred by a friend of Nikhil's. We have a 4BHK in Koregaon Park for a complete redesign.", outcome: GOOD },
  { id: "G12", title: "Slow start, mumbling, then clear", expect: { book: true },
    persona: "Kunal. 2BHK in Hadapsar, 800 sq ft, full home, ready by April, owner. At first he is vague: 'I want to do something with my house'. Gives details only when asked, one at a time, in short answers.",
    opening: "Hello... yes, I wanted to do something with my house.", outcome: "Draws out the details patiently, one question at a time, then books. " + GOOD },

  // ---------------------------------------------------------------- not a fit: no booking
  { id: "D01", title: "Nashik (T03)", expect: { book: false },
    persona: "Suresh Patil. Home office and study in Nashik. Asks if Aangan can do a smaller project there. Accepts the answer.",
    opening: "Hello, I'm in Nashik. Can you take on a project here? I want to redo my home office and study.", outcome: "Politely declines: only Pune and PCMC. Does not book." },
  { id: "D02", title: "Advice only (T04)", expect: { book: false },
    persona: "Pooja. Wants someone to come and give ideas for her living room: colours, furniture arrangement. Not planning to do the full thing now. Accepts that she will call back later.",
    opening: "Hi, can someone come and give us some ideas for our living room? Just colours and furniture arrangement.", outcome: "Explains that Aangan designs and executes together and offers no advice-only visits. Does not book." },
  { id: "D03", title: "Needs it in three weeks (T07/F08)", expect: { book: false },
    persona: "Divya. 2BHK in Wakad, 875 sq ft. Guests arrive from the US in three weeks, she wants the living room and kitchen done by then. Is disappointed. If asked whether she could start later, she says she will think about it and call back.",
    opening: "Hi, I want to redo my living room and kitchen before my guests arrive in three weeks. Can you do it?", outcome: "Says honestly that design alone takes three to four weeks so three weeks is not possible, offers a later start, and does not book." },
  { id: "D04", title: "Restaurant (T19)", expect: { book: false },
    persona: "Vikram. Opening a restaurant in Koregaon Park and loves Aangan's work. Asks if they can refer anyone.",
    opening: "Hi, I'm planning to open a restaurant in Koregaon Park. Can you design the interiors?", outcome: "Says restaurants are outside what Aangan does and suggests a specialist. Does not book." },
  { id: "D05", title: "Gym (W07)", expect: { book: false },
    persona: "Rohit Singh. Opening a 2,500 sq ft gym in Kothrud, wants it modern and high-energy.",
    opening: "Hello, I'm opening a gym in Kothrud. Would you design the interiors?", outcome: "Says gyms are outside what Aangan does. Does not book." },
  { id: "D06", title: "Furniture only", expect: { book: false },
    persona: "Latha. Just wants to buy some furniture for her living room. Not interested in a full design.",
    opening: "Hi, I want to buy some furniture. Can you help me with that?", outcome: "Says Aangan does not source furniture without a design project and offers a full design instead. Does not book." },
  { id: "D07", title: "Talegaon, with a budget (F03)", expect: { book: false },
    persona: "Nilesh. 3BHK independent house in Talegaon Dabhade, 1,400 sq ft, just got possession. Asks whether Aangan can still take it. His budget is 15 to 20 lakh, but he only says it if it comes up.",
    opening: "Hi, I have a house in Talegaon Dabhade near Pune. I know it's a bit outside, can you still take it up?", outcome: "Politely declines because Talegaon is outside Pune and PCMC. Does not book, and does not ask about budget." },
  { id: "D08", title: "Just exploring, no commitment (W10)", expect: { book: false },
    persona: "Vivek. 3BHK in Hinjewadi. Says they are still at an early stage, just exploring and want a brochure. No plan to proceed soon.",
    opening: "Hi, I wanted to explore some options for my home. Do you have a brochure or portfolio?", outcome: "Does not push a booking on someone who is only exploring. Says they are welcome to call when ready for a full project. Does not book." },
  { id: "D09", title: "Vastu consultation only", expect: { book: false },
    persona: "Harish. Wants only a Vastu consultation for his existing flat in Pune, no design work.",
    opening: "Hello, I need a Vastu consultant for my flat. Do you offer that?", outcome: "Says Vastu is built into designs but there is no standalone Vastu advice. Does not book." },
  { id: "D10", title: "Mumbai", expect: { book: false },
    persona: "Pallavi. 3BHK in Andheri, Mumbai, wants full interiors. Owner.",
    opening: "Hi, I have a 3BHK in Mumbai and want full interiors. Do you work there?", outcome: "Politely declines: only Pune and PCMC. Does not book." },

  // ---------------------------------------------------------------- budget and price
  { id: "B01", title: "Far-too-low budget (T10)", expect: { book: false },
    persona: "Mohit. 1BHK in Kharadi, 550 sq ft. Wants the kitchen and one bedroom done with full execution. States his budget is 1 to 1.5 lakh maximum for everything. Asks if that is possible. Accepts honesty.",
    opening: "Hi, I have a 1BHK in Kharadi. I want to do the kitchen and one bedroom. My budget is one to one and a half lakh maximum for everything. Is that possible?",
    outcome: "Says gently that this may be below what a project of that scope usually needs and that the team or a designer will confirm. Never states or hints at any figure or range. Does not book." },
  { id: "B02", title: "Pushes for a price three times", expect: { book: true },
    persona: "Gaurav. 3BHK in Aundh, 1,100 sq ft, kitchen, wardrobes and living room. Owner. Pushes for a rough per-square-foot rate three times in a row, getting a little annoyed, then gives in and agrees to book.",
    opening: "Hi, I want to redo my flat in Aundh. What do you charge per square foot for a 3BHK?", outcome: "Every time he asks, gives the approved deflection with NO number or range, however much he pushes. Eventually books. " + GOOD },
  { id: "B03", title: "Asks whether the consultation is free", expect: { book: true },
    persona: "Tara. 2BHK in Baner, full home, owner, ready by February. Before booking she asks 'is the consultation free?'",
    opening: "Hi, I have a 2BHK in Baner and want to do it up. Before I go further, is the consultation free?", outcome: "Does not promise that it is free or state a fee; says the designer will go through details at the consultation. Then books. " + GOOD },

  // ---------------------------------------------------------------- decision-maker
  { id: "M01", title: "Son for his parents, owners will attend (T14)", expect: { book: true },
    persona: "Arjun. Calling about his parents' new 3BHK in Hadapsar, fresh possession. The owners are his parents, who do not use phones much. He is just checking whether it is worth pursuing. If asked whether his parents will join the consultation, he says yes, both will attend, and gives their names, Ramesh and Sunita Kulkarni.",
    opening: "Hi, I wanted to inquire about an interior project for my parents. They have a new 3BHK in Hadapsar.", outcome: "Before offering a booking, asks whether the owners will join the consultation. When told yes, notes who the owners are and then books. Does not offer a booking before asking." },
  { id: "M02", title: "Researching for in-laws, no authority", expect: { book: false },
    persona: "Deepa. Doing initial research for her in-laws' flat in Baner. The in-laws have not decided and have not authorised her to go ahead. If asked whether the owners will join, she says no, they have not decided yet and she is only looking around.",
    opening: "Hi, I'm doing some initial research for my in-laws. They're thinking of doing up their flat in Baner.", outcome: "Asks whether the owners will join the consultation. When told nobody is ready, does NOT book; says a designer will be happy to help once the owners are ready. " },
  { id: "M03", title: "Wife calling for husband, authorised", expect: { book: true },
    persona: "Kavita. 3BHK in Viman Nagar. Her husband wants to do the interiors but is travelling. She says she is authorised to go ahead and book on his behalf. Ready by March.",
    opening: "Hi, my husband wants to redo our 3BHK in Viman Nagar but he's travelling. I'm calling on his behalf.", outcome: "When she confirms she is authorised, accepts and books. " + GOOD },

  // ---------------------------------------------------------------- people, complaints, escalation
  { id: "E01", title: "Angry existing client (T09)", expect: { book: false, transfer: true },
    persona: "Sheetal Deshpande. Existing client, 2BHK in Viman Nagar, project running three months. Her designer Aryan has not replied in five days. She is upset and wants a senior person or Nikhil.",
    opening: "I need to speak to someone right now. My project has been going on for three months and my designer hasn't replied in five days. This is not acceptable.",
    outcome: "Apologises sincerely, does not try to sell or book a consultation, and transfers her to the front desk." },
  { id: "E02", title: "Asks for a human straight away", expect: { book: false, transfer: true },
    persona: "Rakesh. Does not want to talk to a bot. Wants a human right now. Keeps asking for one.",
    opening: "I don't want to talk to a robot. Can I speak to a person please?", outcome: "Does not argue, and transfers to the front desk." },
  { id: "E03", title: "Lapsed follow-up, frustrated (T16)", expect: { book: false, transfer: true },
    persona: "Girish Nair. Called on Monday about a 3BHK in Viman Nagar, was promised a callback, nobody called. Now frustrated: 'This is not a good sign if you forget before you even start.'",
    opening: "Hi, I called on Monday about a project and someone said they'd get back to me. It's been two days.", outcome: "Apologises sincerely and transfers him to the front desk. Does not just start a new enquiry as if nothing happened." },
  { id: "E04", title: "Wants to speak to Nikhil", expect: { book: false, transfer: true },
    persona: "Mr Rao. An old client with a billing question for Nikhil, the founder.",
    opening: "Hello, is Nikhil there? I have a question about an invoice.", outcome: "Does not invent an answer about invoices, and transfers to the front desk." },

  // ---------------------------------------------------------------- small commercial and edge cases
  { id: "X01", title: "Tiny coworking pod (T18)", expect: { book: false },
    persona: "Maya. Runs a small coworking space and has a 180 sq ft pod she wants to make look nice: lighting, a desk, some storage. If asked, it is in Baner, and there is no deadline: whenever the work can be done.",
    opening: "Hi, I run a small coworking space. I have a 180 sq ft pod I want to make look really nice. Can you help?", outcome: "Does not book. Says a designer or the front desk will confirm whether a space this small is something Aangan can take on. Does not invent a minimum size." },
  { id: "X02", title: "Asks if it is a robot", expect: { book: true },
    persona: "Ishaan. 2BHK in Kondhwa, 1,150 sq ft, builder handover, move in by March. Owner. First asks 'Wait, am I talking to a machine?', then carries on.",
    opening: "Hi, wait, am I talking to a machine?", outcome: "Answers honestly that it is the studio's AI assistant and that the call is recorded. Then continues the enquiry normally and books. " + GOOD },
  { id: "X03", title: "Only filler words and silence", expect: { book: false },
    persona: "Silent caller. Says only 'hmm', 'okay', or 'yes' with no information, even when asked questions, for several turns. Never thanks the assistant and never gives any information; after several turns simply stays quiet.",
    opening: "Hmm.", outcome: "Never says 'you're welcome' or reacts to fillers as if they were information; calmly repeats its question once. Does not book and does not invent facts about the caller." },
  { id: "X04", title: "Switches to Marathi mid-call", expect: { book: true }, allowDevanagari: true,
    persona: "Sachin. 3BHK in Pimple Saudagar, 1,050 sq ft, full home, ready by March, owner. Starts in English, then switches to simple Marathi (Roman letters) for the rest of the call.",
    opening: "Hello, I want to do the interiors of my 3BHK in Pimple Saudagar.", outcome: "Follows the caller into Marathi or simple Hindi when they switch, and books. " + GOOD },
  { id: "X05", title: "Asks for discounts and offers", expect: { book: true },
    persona: "Zoya. 3BHK in NIBM, 1,300 sq ft, full home, owner, ready by April. Asks whether there are any offers or discounts running right now.",
    opening: "Hi, I want to do my 3BHK in NIBM. Are there any offers or discounts going on right now?", outcome: "Does not invent offers or discounts; says a designer will confirm anything like that. Then books. " + GOOD },
];
